#!/bin/bash

set -eu

git clone ${REPO_ROOT} ${REPO_OUT}

if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "${GIT_EMAIL}"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "${GIT_NAME}"
fi

STEMCELL_OS=${STEMCELL_OS:-ubuntu-xenial}
STEMCELL_VERSION=$(cat stemcell/version)

releases=($(ls -d *compiled-release))

for release in "${releases[@]}"; do

  tar -xzf $release/*.tgz $( tar -tzf $release/*.tgz | grep 'release.MF' )
  release_name=$( grep -E '^name: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_version=$( grep -E '^version: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_url=$(cat $release/url)
  release_sha1=$(sha1sum $release/*.tgz | awk '{print $1}')

  pushd ${REPO_OUT}
    ci/scripts/update-manifest-compiled-release $release_name $release_version $release_url $release_sha1 $STEMCELL_OS $STEMCELL_VERSION
  popd
done

pushd ${REPO_OUT}
  git merge --no-edit ${BRANCH}
  git add -A
  git status
  git commit -m "Updated compiled releases for ${STEMCELL_OS}/${STEMCELL_VERSION}"
popd
