#!/bin/bash

HEALTH_RESPONSE=$(curl --max-time 5 --connect-timeout 2 127.0.0.1:8989/healthz)

DATA_DIR=/var/vcap/data/uaa
STATUS_FILE=$DATA_DIR/uaa_status

if [[ $HEALTH_RESPONSE == "ok" && -f $STATUS_FILE ]]
then
  exit 0
elif [[ $HEALTH_RESPONSE == "FAILURE" && -f $STATUS_FILE ]]
then
  exit 2
else
  exit 1
fi