#!/bin/bash

WHEN_FINISH=when-finish.timestamp
WHEN_NOW=when-now.timestamp

delete_ts_files() {
  rm -f $WHEN_FINISH
  rm -f $WHEN_NOW
  echo "uaa-post-start - cleaned up timestamp files"
}

touch -d "10 minutes" $WHEN_FINISH
touch $WHEN_NOW
EXPIRATION=`ls -la --full-time $WHEN_FINISH |awk '{print $6 " " $7}'`
echo "uaa-post-start - performing post start healthcheck until $EXPIRATION"

while [ $WHEN_NOW -ot $WHEN_FINISH ]; do
    /var/vcap/jobs/uaa/bin/health_check
    if [ $? == 0 ]
    then
        delete_ts_files
        echo "uaa-post-start - post start health check successful"
        exit 0
    fi
    sleep 1
    touch $WHEN_NOW
done
echo "uaa-post-start - post start health check failed"
delete_ts_files
exit 1